FROM php:7.4-apache

EXPOSE 80

COPY home.php /var/www/html/

RUN chmod -R 774 /var/www/ && chown www-data /var/www/ -R

RUN apt-get update

RUN docker-php-ext-install mysqli

RUN docker-php-ext-enable mysqli

RUN apachectl restart
